/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/marco/catkin_ws/src/vision/srv/FindObject.srv
 *
 */


#ifndef VISION_MESSAGE_FINDOBJECT_H
#define VISION_MESSAGE_FINDOBJECT_H

#include <ros/service_traits.h>


#include <vision/FindObjectRequest.h>
#include <vision/FindObjectResponse.h>


namespace vision
{

struct FindObject
{

typedef FindObjectRequest Request;
typedef FindObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindObject
} // namespace vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision::FindObject > {
  static const char* value()
  {
    return "b20c6a08bb4b6fbb03f43969b46e84e1";
  }

  static const char* value(const ::vision::FindObject&) { return value(); }
};

template<>
struct DataType< ::vision::FindObject > {
  static const char* value()
  {
    return "vision/FindObject";
  }

  static const char* value(const ::vision::FindObject&) { return value(); }
};


// service_traits::MD5Sum< ::vision::FindObjectRequest> should match 
// service_traits::MD5Sum< ::vision::FindObject > 
template<>
struct MD5Sum< ::vision::FindObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision::FindObject >::value();
  }
  static const char* value(const ::vision::FindObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::FindObjectRequest> should match 
// service_traits::DataType< ::vision::FindObject > 
template<>
struct DataType< ::vision::FindObjectRequest>
{
  static const char* value()
  {
    return DataType< ::vision::FindObject >::value();
  }
  static const char* value(const ::vision::FindObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision::FindObjectResponse> should match 
// service_traits::MD5Sum< ::vision::FindObject > 
template<>
struct MD5Sum< ::vision::FindObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision::FindObject >::value();
  }
  static const char* value(const ::vision::FindObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::FindObjectResponse> should match 
// service_traits::DataType< ::vision::FindObject > 
template<>
struct DataType< ::vision::FindObjectResponse>
{
  static const char* value()
  {
    return DataType< ::vision::FindObject >::value();
  }
  static const char* value(const ::vision::FindObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MESSAGE_FINDOBJECT_H
