/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/marco/catkin_ws/src/vision/srv/GetObjectsInScene.srv
 *
 */


#ifndef VISION_MESSAGE_GETOBJECTSINSCENE_H
#define VISION_MESSAGE_GETOBJECTSINSCENE_H

#include <ros/service_traits.h>


#include <vision/GetObjectsInSceneRequest.h>
#include <vision/GetObjectsInSceneResponse.h>


namespace vision
{

struct GetObjectsInScene
{

typedef GetObjectsInSceneRequest Request;
typedef GetObjectsInSceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetObjectsInScene
} // namespace vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision::GetObjectsInScene > {
  static const char* value()
  {
    return "9606dc4cf29ccfc019371d2907786218";
  }

  static const char* value(const ::vision::GetObjectsInScene&) { return value(); }
};

template<>
struct DataType< ::vision::GetObjectsInScene > {
  static const char* value()
  {
    return "vision/GetObjectsInScene";
  }

  static const char* value(const ::vision::GetObjectsInScene&) { return value(); }
};


// service_traits::MD5Sum< ::vision::GetObjectsInSceneRequest> should match 
// service_traits::MD5Sum< ::vision::GetObjectsInScene > 
template<>
struct MD5Sum< ::vision::GetObjectsInSceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision::GetObjectsInScene >::value();
  }
  static const char* value(const ::vision::GetObjectsInSceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::GetObjectsInSceneRequest> should match 
// service_traits::DataType< ::vision::GetObjectsInScene > 
template<>
struct DataType< ::vision::GetObjectsInSceneRequest>
{
  static const char* value()
  {
    return DataType< ::vision::GetObjectsInScene >::value();
  }
  static const char* value(const ::vision::GetObjectsInSceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision::GetObjectsInSceneResponse> should match 
// service_traits::MD5Sum< ::vision::GetObjectsInScene > 
template<>
struct MD5Sum< ::vision::GetObjectsInSceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision::GetObjectsInScene >::value();
  }
  static const char* value(const ::vision::GetObjectsInSceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::GetObjectsInSceneResponse> should match 
// service_traits::DataType< ::vision::GetObjectsInScene > 
template<>
struct DataType< ::vision::GetObjectsInSceneResponse>
{
  static const char* value()
  {
    return DataType< ::vision::GetObjectsInScene >::value();
  }
  static const char* value(const ::vision::GetObjectsInSceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MESSAGE_GETOBJECTSINSCENE_H
