/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/marco/catkin_ws/src/vision/srv/Match.srv
 *
 */


#ifndef VISION_MESSAGE_MATCH_H
#define VISION_MESSAGE_MATCH_H

#include <ros/service_traits.h>


#include <vision/MatchRequest.h>
#include <vision/MatchResponse.h>


namespace vision
{

struct Match
{

typedef MatchRequest Request;
typedef MatchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Match
} // namespace vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision::Match > {
  static const char* value()
  {
    return "b7518446bf6d83748ddcb8b0379807c6";
  }

  static const char* value(const ::vision::Match&) { return value(); }
};

template<>
struct DataType< ::vision::Match > {
  static const char* value()
  {
    return "vision/Match";
  }

  static const char* value(const ::vision::Match&) { return value(); }
};


// service_traits::MD5Sum< ::vision::MatchRequest> should match 
// service_traits::MD5Sum< ::vision::Match > 
template<>
struct MD5Sum< ::vision::MatchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Match >::value();
  }
  static const char* value(const ::vision::MatchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::MatchRequest> should match 
// service_traits::DataType< ::vision::Match > 
template<>
struct DataType< ::vision::MatchRequest>
{
  static const char* value()
  {
    return DataType< ::vision::Match >::value();
  }
  static const char* value(const ::vision::MatchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision::MatchResponse> should match 
// service_traits::MD5Sum< ::vision::Match > 
template<>
struct MD5Sum< ::vision::MatchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Match >::value();
  }
  static const char* value(const ::vision::MatchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::MatchResponse> should match 
// service_traits::DataType< ::vision::Match > 
template<>
struct DataType< ::vision::MatchResponse>
{
  static const char* value()
  {
    return DataType< ::vision::Match >::value();
  }
  static const char* value(const ::vision::MatchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MESSAGE_MATCH_H
