/* Auto-generated by genmsg_cpp for file /home/marco/catkin_ws/src/pi_vision/pi_face_tracker/srv/KeyCommand.srv */
#ifndef PI_FACE_TRACKER_SERVICE_KEYCOMMAND_H
#define PI_FACE_TRACKER_SERVICE_KEYCOMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace pi_face_tracker
{
template <class ContainerAllocator>
struct KeyCommandRequest_ {
  typedef KeyCommandRequest_<ContainerAllocator> Type;

  KeyCommandRequest_()
  : command()
  {
  }

  KeyCommandRequest_(const ContainerAllocator& _alloc)
  : command(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  command;


  typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct KeyCommandRequest
typedef  ::pi_face_tracker::KeyCommandRequest_<std::allocator<void> > KeyCommandRequest;

typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandRequest> KeyCommandRequestPtr;
typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandRequest const> KeyCommandRequestConstPtr;



template <class ContainerAllocator>
struct KeyCommandResponse_ {
  typedef KeyCommandResponse_<ContainerAllocator> Type;

  KeyCommandResponse_()
  {
  }

  KeyCommandResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct KeyCommandResponse
typedef  ::pi_face_tracker::KeyCommandResponse_<std::allocator<void> > KeyCommandResponse;

typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandResponse> KeyCommandResponsePtr;
typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandResponse const> KeyCommandResponseConstPtr;


struct KeyCommand
{

typedef KeyCommandRequest Request;
typedef KeyCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct KeyCommand
} // namespace pi_face_tracker

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pi_face_tracker::KeyCommandRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pi_face_tracker::KeyCommandRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pi_face_tracker::KeyCommandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const  ::pi_face_tracker::KeyCommandRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::pi_face_tracker::KeyCommandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pi_face_tracker/KeyCommandRequest";
  }

  static const char* value(const  ::pi_face_tracker::KeyCommandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pi_face_tracker::KeyCommandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string command\n\
\n\
";
  }

  static const char* value(const  ::pi_face_tracker::KeyCommandRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pi_face_tracker/KeyCommandResponse";
  }

  static const char* value(const  ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pi_face_tracker::KeyCommandRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.command);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct KeyCommandRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct KeyCommandResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<pi_face_tracker::KeyCommand> {
  static const char* value() 
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const pi_face_tracker::KeyCommand&) { return value(); } 
};

template<>
struct DataType<pi_face_tracker::KeyCommand> {
  static const char* value() 
  {
    return "pi_face_tracker/KeyCommand";
  }

  static const char* value(const pi_face_tracker::KeyCommand&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<pi_face_tracker::KeyCommandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const pi_face_tracker::KeyCommandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<pi_face_tracker::KeyCommandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pi_face_tracker/KeyCommand";
  }

  static const char* value(const pi_face_tracker::KeyCommandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<pi_face_tracker::KeyCommandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const pi_face_tracker::KeyCommandResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<pi_face_tracker::KeyCommandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pi_face_tracker/KeyCommand";
  }

  static const char* value(const pi_face_tracker::KeyCommandResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // PI_FACE_TRACKER_SERVICE_KEYCOMMAND_H

