!obj:pylearn2.train.Train {
    dataset: &train 

 
 !obj:pylearn2.datasets.transformer_dataset.TransformerDataset { 
 raw: 
       !obj:pylearn2.datasets.transformer_dataset.TransformerDataset {
            raw: !obj:pylearn2.datasets.cifar10.CIFAR10 {
                which_set: 'train',
                start: 0,
                stop: 8000
            },
            transformer: !pkl: "./dae_l1.pkl"
        },
        transformer: !pkl: "./dae_l2.pkl"
},

    model: !obj:pylearn2.models.autoencoder.DenoisingAutoencoder {
        nvis : 1024,
        nhid : 512,
        irange : 0.05,
        corruptor: !obj:pylearn2.corruption.BinomialCorruptor {
            corruption_level: .3,
        },
        act_enc: "tanh",
        act_dec: null,    # Linear activation on the decoder side.
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate : 1e-3,
        batch_size : 100,
        monitoring_batches : 5,
        monitoring_dataset : *train,
        cost : !obj:pylearn2.costs.autoencoder.MeanSquaredReconstructionError {},
        termination_criterion : !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: 10,
        },
    },
    save_path: "./dae_l3.pkl",
    save_freq: 1
}
