set(_CATKIN_CURRENT_PACKAGE "talos_machinelearning")
set(talos_machinelearning_MAINTAINER "marco <noobaca2@gmail.com>")
set(talos_machinelearning_DEPRECATED "")
set(talos_machinelearning_VERSION "0.0.0")
set(talos_machinelearning_BUILD_DEPENDS "sensor_msgs" "geometry_msgs" "roscpp" "nodelet" "image_transport" "opencv2" "message_runtime")
set(talos_machinelearning_RUN_DEPENDS "sensor_msgs" "geometry_msgs" "roscpp" "nodelet" "image_transport" "opencv2" "message_runtime")
set(talos_machinelearning_BUILDTOOL_DEPENDS "catkin")