set(_CATKIN_CURRENT_PACKAGE "talos_machinelearning")
set(talos_machinelearning_MAINTAINER "marco <marco@todo.todo>")
set(talos_machinelearning_DEPRECATED "")
set(talos_machinelearning_VERSION "0.0.0")
set(talos_machinelearning_BUILD_DEPENDS )
set(talos_machinelearning_RUN_DEPENDS )
set(talos_machinelearning_BUILDTOOL_DEPENDS "catkin")