set(_CATKIN_CURRENT_PACKAGE "emergency_stop")
set(emergency_stop_MAINTAINER "Justin Wang <hzjustin@hotmail.com>")
set(emergency_stop_DEPRECATED "")
set(emergency_stop_VERSION "0.0.0")
set(emergency_stop_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(emergency_stop_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(emergency_stop_BUILDTOOL_DEPENDS "catkin")