set(_CATKIN_CURRENT_PACKAGE "vision")
set(vision_MAINTAINER "Devon Ash <noobaca2@gmail.com>")
set(vision_DEPRECATED "")
set(vision_VERSION "0.0.0")
set(vision_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "sensor_msgs" "nodelet" "image_transport" "opencv2" "gtest" "message_generation")
set(vision_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "sensor_msgs" "nodelet" "image_transport" "opencv2" "gtest" "message_runtime")
set(vision_BUILDTOOL_DEPENDS "catkin")