(cl:defpackage vision-srv
  (:use )
  (:export
   "FINDOBJECT"
   "<FINDOBJECT-REQUEST>"
   "FINDOBJECT-REQUEST"
   "<FINDOBJECT-RESPONSE>"
   "FINDOBJECT-RESPONSE"
   "MATCH"
   "<MATCH-REQUEST>"
   "MATCH-REQUEST"
   "<MATCH-RESPONSE>"
   "MATCH-RESPONSE"
   "GETOBJECTSINSCENE"
   "<GETOBJECTSINSCENE-REQUEST>"
   "GETOBJECTSINSCENE-REQUEST"
   "<GETOBJECTSINSCENE-RESPONSE>"
   "GETOBJECTSINSCENE-RESPONSE"
   "CONTAINS"
   "<CONTAINS-REQUEST>"
   "CONTAINS-REQUEST"
   "<CONTAINS-RESPONSE>"
   "CONTAINS-RESPONSE"
  ))

